config:
  install_tree: 
    root: $HOME/spack-workspace/software
  source_cache: $HOME/.spack/cache
  module_roots:
    tcl: $HOME/spack-workspace/modules/tcl
    lmod: $HOME/spack-workspace/modules/lmod
